http:
  routers:
    to-dev-server:
      service: dev-server
      entryPoints:
        - websecure
      rule: Host(`dev.your-domain.com`) # domain at which the local dev server should be reachable
      tls:
        certResolver: myresolver

  services:
    dev-server:
      loadBalancer:
        servers:
        - url: http://host.docker.internal:8000 # port of the local dev server
